apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
      tier: backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodeapp
        tier: backend
    spec:
      containers:
      - name: master
        image: ardih/nodeapp:port.10
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
    tier: backend
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 3000
  selector:
    app: nodeapp
    tier: backend
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
  - host: "ardih.id"
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: nodeapp
          servicePort: 9000