apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-v2
  labels:
    app: nodeapp
    version: v2
spec:
  selector:
    matchLabels:
      app: nodeapp
      version: v2
      tier: backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodeapp
        version: v2
        tier: backend
    spec:
      containers:
      - name: master
        image: ardih/nodeapp:v2.1
        imagePullPolicy: Never
        env: 
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000

---