apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
  labels:
    app: phpapp
spec:
  selector:
    matchLabels:
      app: phpapp
      tier: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: phpapp
        tier: frontend
    spec:
      containers:
      - name: phpapp
        image: ardih/phpapp:env.22
        imagePullPolicy: Never
        env:
        - name: GET_HOSTS_FROM
          value: "nodeapp:9000"
        - name: NODE_SERVICE
          value: "http://ardih.id/api/" # service nodeapp
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: phpapp
  labels:
    app: phpapp
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: phpapp
    tier: frontend
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   name: phpapp-master
# spec:
#   rules:
#   - host: servicemesh.demo
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: phpapp
#           servicePort: 80