apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-master
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: 985656090346.dkr.ecr.ap-southeast-2.amazonaws.com/nodeapp:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-master
  labels:
    app: nodeapp
    role: master
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nodeapp
    role: master
    tier: backend
