pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID="xxx"
        AWS_DEFAULT_REGION="ap-southeast-3"
        IMAGE_REPO_NAME="phpapp"
        IMAGE_TAG="2"
        REPOSITORY_URI = "xxx.dkr.ecr.ap-southeast-3.amazonaws.com/phpapp"
    }
   
    stages {
        
         stage('Logging into AWS ECR') {
            steps {
                script {
                sh """aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"""
                }
                 
            }
        }

        stage('Cloning Git') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '', url: 'https://github.com/immma/phpapp.git']]])     
            }
        }

        stage('Building image') {
            steps{
                script {
                dockerImage = docker.build "${IMAGE_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage('Tag images') {
            steps{
                script {
                sh """docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:$IMAGE_TAG"""
                }
            }
        }

        stage('Tag images') {
            steps{
                script {
                sh """docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}"""
                }
            }
        }

    }
}